const ItemDB: any = [
    {
        id: 1,
        image: './src/assets/menShoe1.webp',
        name: 'Adidas Men\'s Casual Shoe',
        gender: 'Men',
        category: 'Sports',
        price: 'Rs.8,999.00',
        status: 'New Arrivals',
        quantity: '10',
    },
    {
        id: 2,
        image: './src/assets/menShoe2.png',
        name: 'Adidas Men\'s Casual Shoe',
        gender: 'Men',
        category: 'Sports',
        price: 'Rs.8,499.00',
        status: 'New Arrivals',
        quantity: '10',
    },
    {
        id: 3,
        image: './src/assets/menShoe3.png',
        name: 'Adidas Men\'s Casual Shoe',
        gender: 'Men',
        category: 'Sports',
        price: 'Rs.8,999.00',
        status: 'New Arrivals',
        quantity: '10',
    },
    {
        id: 4,
        image: './src/assets/menShoe4.png',
        name: 'Adidas Men\'s Casual Shoe',
        gender: 'Men',
        category: 'Sports',
        price: 'Rs.8,999.00',
        status: 'New Arrivals',
        quantity: '10',
    },
    {
        id: 5,
        image: './src/assets/menShoe5.png',
        name: 'Adidas Men\'s Casual Shoe',
        gender: 'Men',
        category: 'Sports',
        price: 'Rs.8,999.00',
        status: 'No sale',
        quantity: '10',
    },
    {
        id: 6,
        image: './src/assets/menShoe6.png',
        name: 'Adidas Men\'s Casual Shoe',
        gender: 'Men',
        category: 'Sports',
        price: 'Rs.8,999.00',
        status: 'No sale',
        quantity: '10',
    },
    {
        id: 7,
        image: './src/assets/menShoe7.png',
        name: 'Adidas Men\'s Casual Shoe',
        gender: 'Men',
        category: 'Sports',
        price: 'Rs.8,999.00',
        status: 'Sale',
        quantity: '10',
    },
    {
        id: 8,
        image: './src/assets/menShoe8.png',
        name: 'Adidas Men\'s Casual Shoe',
        gender: 'Men',
        category: 'Sports',
        price: 'Rs.11,999.00',
        status: 'No sale',
        quantity: '10',
    },
    {
        id: 9,
        image: './src/assets/menShoe9.png',
        name: 'Adidas Men\'s Casual Shoe',
        gender: 'Men',
        category: 'Sports',
        price: 'Rs.11,999.00',
        status: 'No sale',
        quantity: '10',
    },
    {
        id: 10,
        image: './src/assets/menShoe10.png',
        name: 'Adidas Men\'s Casual Shoe',
        gender: 'Men',
        category: 'Sports',
        price: 'Rs.9,999.00',
        status: 'Sale',
        quantity: '10',
    },
    {
        id: 11,
        image: './src/assets/menNikeShoe1.png',
        name: 'Nike Men\'s Casual Shoe',
        gender: 'Men',
        category: 'Sports',
        price: 'Rs.8,499.00',
        status: 'No sale',
        quantity: '10',
    },
    {
        id: 12,
        image: './src/assets/menNikeShoe2.png',
        name: 'Nike Men\'s Casual Shoe',
        gender: 'Men',
        category: 'Sports',
        price: 'Rs.8,499.00',
        status: 'New Arrivals',
        quantity: '10',
    },
    {
        id: 13,
        image: './src/assets/menNikeShoe3.png',
        name: 'Nike Men\'s Casual Shoe',
        gender: 'Men',
        category: 'Sports',
        price: 'Rs.8,499.00',
        status: 'New Arrivals',
        quantity: '10',
    },
    {
        id: 14,
        image: './src/assets/menNikeShoe4.png',
        name: 'Nike Men\'s Casual Shoe',
        gender: 'Men',
        category: 'Sports',
        price: 'Rs.8,499.00',
        status: 'New Arrivals',
        quantity: '10',
    },
    {
        id: 15,
        image: './src/assets/menNikeShoe5.png',
        name: 'Nike Men\'s Casual Shoe',
        gender: 'Men',
        category: 'Sports',
        price: 'Rs.8,499.00',
        status: 'New Arrivals',
        quantity: '10',
    },
    {
        id: 16,
        image: './src/assets/menNikeShoe6.png',
        name: 'Nike Men\'s Casual Shoe',
        gender: 'Men',
        category: 'Sports',
        price: 'Rs.8,499.00',
        status: 'No sale',
        quantity: '10',
    },
    {
        id: 17,
        image: './src/assets/menNikeShoe7.png',
        name: 'Nike Men\'s Casual Shoe',
        gender: 'Men',
        category: 'Sports',
        price: 'Rs.8,499.00',
        status: 'No sale',
        quantity: '10',
    },
    {
        id: 18,
        image: './src/assets/menNikeShoe8.png',
        name: 'Nike Men\'s Casual Shoe',
        gender: 'Men',
        category: 'Sports',
        price: 'Rs.8,499.00',
        status: 'No sale',
        quantity: '10',
    },
    {
        id: 19,
        image: './src/assets/menNikeShoe9.png',
        name: 'Nike Men\'s Casual Shoe',
        gender: 'Men',
        category: 'Sports',
        price: 'Rs.8,499.00',
        status: 'Sale',
        quantity: '10',
    },
    {
        id: 20,
        image: './src/assets/menNikeShoe10.png',
        name: 'Nike Men\'s Casual Shoe',
        gender: 'Men',
        category: 'Sports',
        price: 'Rs.8,499.00',
        status: 'Sale',
        quantity: '10',
    },
    {
        id: 21,
        image: './src/assets/womenShoe1.jpeg',
        name: 'Low Block Heel Sandal',
        gender: 'Women',
        category: 'Casual',
        price: 'Rs.2,299.00',
        status: '',
        quantity: '10',
    },
    {
        id: 22,
        image: './src/assets/womenShoe2.jpeg',
        name: 'Wide Fit Flats',
        gender: 'Women',
        category: 'Casual',
        price: 'Rs.1,499.00',
        status: 'Sale',
        quantity: '10',
    },
    {
        id: 23,
        image: './src/assets/womenShoe3.jpeg',
        name: 'Flat Slippers',
        gender: 'Women',
        category: 'Casual',
        price: 'Rs.1,199.00',
        status: '',
        quantity: '10',
    },
    {
        id: 24,
        image: './src/assets/womenShoe4.jpeg',
        name: 'Luxury Pink High Heel',
        gender: 'Women',
        size: '10/44',
        category: 'Party',
        price: 'Rs.6,499.00',
        status: '',
        quantity: '10',
    },
    {
        id: 25,
        image: './src/assets/womenShoe5.jpeg',
        name: 'Pink Slippers',
        gender: 'Women',
        category: 'Casual',
        price: 'Rs.1,199.00',
        status: 'Sale',
        quantity: '10',
    },
    {
        id: 26,
        image: './src/assets/womenShoe6.jpeg',
        name: 'High Heel Shoe',
        gender: 'Women',
        category: 'Casual',
        price: 'Rs.4,999.00',
        status: 'Sale',
        quantity: '10',
    },
    {
        id: 27,
        image: './src/assets/womenShoe7.jpeg',
        name: 'Pumps Women Heels',
        gender: 'Women',
        category: 'Office',
        price: 'Rs.3,199.00',
        status: '',
        quantity: '10',
    },
    {
        id: 28,
        image: './src/assets/womenShoe8.jpeg',
        name: 'Women\'s Casual Rubber Slippers',
        gender: 'Women',
        category: 'Office',
        price: 'Rs.499.00',
        status: 'Sale',
        quantity: '10',
    },
    {
        id: 29,
        image: './src/assets/womenShoe9.jpeg',
        name: 'Gold Sandal Shoes',
        gender: 'Women',
        category: 'Party',
        price: 'Rs.12,499.00',
        status: '',
        quantity: '10',
    },
    {
        id: 30,
        image: './src/assets/womenShoe10.jpeg',
        name: 'Pink flip flops',
        gender: 'Women',
        category: 'Casual',
        price: 'Rs.899.00',
        status: 'Sale',
        quantity: '10',
    },
    {
        id: 31,
        image: './src/assets/womenShoe11.jpeg',
        name: 'Women\'s Coat Shoes White',
        gender: 'Women',
        category: 'Casual',
        price: 'Rs.3,499.00',
        status: 'Sale',
        quantity: '10',
    },
    {
        id: 32,
        image: './src/assets/womenShoe12.jpeg',
        name: 'Women\'s Andre Assous Shoes',
        gender: 'Women',
        category: 'Casual',
        price: 'Rs.999.00',
        status: 'Sale',
        quantity: '10',
    },
    {
        id: 33,
        image: './src/assets/womenShoe13.jpeg',
        name: 'Adiver Women\'s Flats Slippers',
        gender: 'Women',
        category: 'Casual',
        price: 'Rs.1,499.00',
        status: '',
        quantity: '10',
    },
    {
        id: 34,
        image: './src/assets/womenShoe14.jpeg',
        name: 'Roger Vivier Women Heels',
        gender: 'Women',
        category: 'Party',
        price: 'Rs.5,499.00',
        status: '',
        quantity: '10',
    },
    {
        id: 35,
        image: './src/assets/womenShoe15.jpeg',
        name: 'White High Heels Shoes',
        gender: 'Women',
        category: 'Party',
        price: 'Rs.4,499.00',
        status: '',
        quantity: '10',
    },
    {
        id: 36,
        image: './src/assets/womenShoe16.jpeg',
        name: 'Black High Heels Shoes',
        gender: 'Women',
        category: 'Party',
        price: 'Rs.4,499.00',
        status: '',
        quantity: '10',
    },
    {
        id: 37,
        image: './src/assets/womenShoe17.jpeg',
        name: 'Ladies Casual Shoes',
        gender: 'Women',
        category: 'Casuals',
        price: 'Rs.3,499.00',
        status: 'Sale',
        quantity: '10',
    },
    {
        id: 38,
        image: './src/assets/womenShoe18.jpeg',
        name: 'Women\'s Synthetic Leather Casuals',
        gender: 'Women',
        category: 'Casual',
        price: 'Rs.8,499.00',
        status: 'Sale',
        quantity: '10',
    },
    {
        id: 39,
        image: './src/assets/womenShoe19.jpeg',
        name: 'Heels Sandals',
        gender: 'Women',
        category: 'Casual',
        price: 'Rs.2,299.00',
        status: 'Sale',
        quantity: '10',
    },
    {
        id: 40,
        image: './src/assets/womenShoe20.jpeg',
        name: 'Sandy Black Slipper',
        gender: 'Women',
        category: 'Casual',
        price: 'Rs.2,499.00',
        status: '',
        quantity: '10',
    },
    {
        id: 41,
        image: './src/assets/kidsShoe1.jpeg',
        name: 'Children\'s Shoes-adidas tensaur run',
        gender: 'Kids',
        category: 'Casual',
        price: 'Rs.2,499.00',
        status: 'Sale',
        quantity: '10',
    },
    {
        id: 42,
        image: './src/assets/kidsShoe2.jpeg',
        name: 'Children\'s Royalty Shoes',
        gender: 'Kids',
        category: 'Casual',
        price: 'Rs.2,499.00',
        status: 'Sale',
        quantity: '10',
    },
    {
        id: 43,
        image: './src/assets/kidsShoe3.jpeg',
        name: 'Children\'s Casual Shoes',
        gender: 'Kids',
        category: 'Casual',
        price: 'Rs.2,499.00',
        status: '',
        quantity: '10',
    },
    {
        id: 44,
        image: './src/assets/kidsShoe4.jpeg',
        name: 'Children\'s Casual Shoes',
        gender: 'Kids',
        category: 'Casual',
        price: 'Rs.2,499.00',
        status: 'Sale',
        quantity: '10',
    },
    {
        id: 45,
        image: './src/assets/kidsShoe5.jpeg',
        name: 'Yellow Kids Shoes',
        gender: 'Kids',
        category: 'Casual',
        price: 'Rs.2,499.00',
        status: 'Sale',
        quantity: '10',
    },
    {
        id: 46,
        image: './src/assets/kidsShoe6.jpeg',
        name: 'Sport Shoes',
        gender: 'Kids',
        category: 'Sport',
        price: 'Rs.2,499.00',
        status: 'Sale',
        quantity: '10',
    },
    {
        id: 47,
        image: './src/assets/kidsShoe7.jpeg',
        name: 'White Sneakers',
        gender: 'Kids',
        category: 'Casual',
        price: 'Rs.9,499.00',
        status: '',
        quantity: '10',
    },
    {
        id: 48,
        image: './src/assets/kidsShoe8.jpeg',
        name: 'Kids Keen Shoes',
        gender: 'Kids',
        category: 'Casual',
        price: 'Rs.2,499.00',
        status: 'Sale',
        quantity: '10',
    },
    {
        id: 49,
        image: './src/assets/kidsShoe9.jpeg',
        name: 'Baby Shoes',
        gender: 'Kids',
        category: 'Casual',
        price: 'Rs.2,499.00',
        status: '',
        quantity: '10',
    },
    {
        id: 50,
        image: './src/assets/kidsShoe10.jpeg',
        name: 'Nike Giannis Shoes',
        gender: 'Kids',
        category: 'Casual',
        price: 'Rs.2,499.00',
        status: 'Sale',
        quantity: '10',
    }
];

export default ItemDB;